rpc_url = "https://api.mainnet-beta.solana.com"
ws_url = "wss://api.mainnet-beta.solana.com"
periodic_resync_min = 30
out_dir = "./outbox"
probe_amount = 1000000
quote_mints = []

[hype]
bucket_secs = 10
window60s = 60
window300s = 300
w_swaps = 0.35
w_unique = 0.35
w_bsr = 0.20
w_lp = 0.10

[policy]
require_freeze_authority_none = true
forbid_non_transferable = true
forbid_default_frozen = true
forbid_permanent_delegate = true
forbid_transfer_hook = true
forbid_confidential = true
max_fee_bps = 100
max_fee_absolute = 0
allow_mint_authority = false
forbid_memo_required_if_route_has_no_memo = true
forbid_mint_close_authority = false

[[telegram]]
TG_BOT_TOKEN=""
TG_CHANNEL_ID=""

[[programs]]
kind = "OrcaWhirlpools"
id = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"

[[programs]]
kind = "RaydiumClmm"
id = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"

[[programs]]
kind = "RaydiumCpmm"
id = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
